### ISSUE TITLE
response.changes() doesn't return the correct values

### ISSUE THREAD

**Issue by mazondo** [stretchr/sdk-js#16]
The backbone code looks for change info in `response["~changes"]`, but the stretchr sdk right now looks in `response.data()["~changes"]`.  The fixtures in stretchr suggest that `response["~changes"]` is right.

Wanted to check with @matryer before i make the change, is there a change upcoming I should know about?

**Comment by matryer** [comment]
This is well spotted.  Will fix now.

**Comment by mazondo** [comment]
verified.
