### ISSUE TITLE
Figure out how to handle payloads that are too long for the URL string

### ISSUE THREAD

**Issue by tylerstillwater** [stretchr/sdk-js#6]
If you try to send a payload over jsonp with the body in the URL string that is too long, everything goes to hell.

We need to figure out how to get that data to the server in a reliable way that isn't affected by size.

**Comment by matryer** [comment]
Ideally, the data wouldn't be that big. If it is, a different design might be a better solution. 

Otherwise, some browsers will support actual HTTP Post (and not JSONP) which will avoid this. 

Mat

**Comment by matryer** [comment]
The real solution is to write an additional Transport object that uses real AJAX methods (with real HTTP methods) and not JSONP.  This could be done now.

**Comment by matryer** [comment]
This is to be done for Node.js
